In this notebook, I am going to write an LU decomposition algorithm. Written by Jordan Ehrman, Nov 6th 2020. 

In [36]:
import numpy as np 
from copy import deepcopy

In [56]:
testmat = np.random.rand(5,5)

In [82]:
testmat

array([[0.13053584, 0.22240024, 0.05663956, 0.42365499, 0.2563159 ],
       [0.98522742, 0.18128525, 0.60483977, 0.27436262, 0.77830831],
       [0.25232466, 0.88872072, 0.74594817, 0.15359958, 0.9956002 ],
       [0.74710112, 0.52519887, 0.56575797, 0.16913854, 0.19932893],
       [0.35317592, 0.10162126, 0.83147115, 0.90756459, 0.38763804]])

Starting off with some scratch space on my testmat

In [86]:
dummytestmat = deepcopy(testmat)
rows,columns = np.shape(dummytestmat)
I = np.eye(rows,columns)
listofP = []
for column in range(columns):
    rowmax = np.argmax(dummytestmat[column:,column])+column
    print(rowmax)
    tempP = deepcopy(I)
    tempP[column,:] = I[rowmax,:]
    tempP[rowmax,:] = I[column,:]
    print(tempP)
    listofP.append(deepcopy(tempP))
    dummytestmat = tempP.dot(dummytestmat)

1
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [101]:
totP = listofP[columns-1]
for i in range(columns-2,-1,-1):
    print(i)
    totP = totP.dot(listofP[i])

3
2
1
0


In [103]:
totP.dot(testmat)

array([[0.98522742, 0.18128525, 0.60483977, 0.27436262, 0.77830831],
       [0.25232466, 0.88872072, 0.74594817, 0.15359958, 0.9956002 ],
       [0.35317592, 0.10162126, 0.83147115, 0.90756459, 0.38763804],
       [0.13053584, 0.22240024, 0.05663956, 0.42365499, 0.2563159 ],
       [0.74710112, 0.52519887, 0.56575797, 0.16913854, 0.19932893]])

That's how I get the permutation matrix! Let me define it as a function to use later. 

In [106]:
def findP(testmat):
    dummytestmat = deepcopy(testmat)
    rows,columns = np.shape(dummytestmat)
    I = np.eye(rows,columns)
    listofP = []
    for column in range(columns):
        rowmax = np.argmax(dummytestmat[column:,column])+column
        tempP = deepcopy(I)
        tempP[column,:] = I[rowmax,:]
        tempP[rowmax,:] = I[column,:]
        listofP.append(deepcopy(tempP))
        dummytestmat = tempP.dot(dummytestmat)
    totP = listofP[columns-1]
    for i in range(columns-2,-1,-1):
        totP = totP.dot(listofP[i])
    return totP

In [107]:
testP = findP(testmat)
testP.dot(testmat)

array([[0.98522742, 0.18128525, 0.60483977, 0.27436262, 0.77830831],
       [0.25232466, 0.88872072, 0.74594817, 0.15359958, 0.9956002 ],
       [0.35317592, 0.10162126, 0.83147115, 0.90756459, 0.38763804],
       [0.13053584, 0.22240024, 0.05663956, 0.42365499, 0.2563159 ],
       [0.74710112, 0.52519887, 0.56575797, 0.16913854, 0.19932893]])

# Perfect! Moving on to LUD

In [215]:
newtestmat = deepcopy(testP.dot(testmat))

In [216]:
dummytestmat = deepcopy(newtestmat)
rows,columns = np.shape(newtestmat)
listofl = []
listoflinvs = []
I = np.eye(rows,columns)
for column in range(columns):
    tempL = deepcopy(I)
    tempLinv = deepcopy(I)
    for row in range(rows-column-1):
        tempL[row+1+column,column] = dummytestmat[row+1+column,column] / dummytestmat[column,column]
        tempLinv[row+1+column,column] = - dummytestmat[row+1+column,column] / dummytestmat[column,column]
    listofl.append(deepcopy(tempL))
    listoflinvs.append(deepcopy(tempLinv))
    dummytestmat = tempLinv.dot(dummytestmat)
    print(dummytestmat)

[[ 0.98522742  0.18128525  0.60483977  0.27436262  0.77830831]
 [ 0.          0.84229211  0.59104384  0.08333311  0.79626919]
 [ 0.          0.03663567  0.61465335  0.80921341  0.10863672]
 [ 0.          0.19838119 -0.02349754  0.38730383  0.15319541]
 [ 0.          0.38772968  0.10710603 -0.03891151 -0.39086476]]
[[ 0.98522742  0.18128525  0.60483977  0.27436262  0.77830831]
 [ 0.          0.84229211  0.59104384  0.08333311  0.79626919]
 [ 0.          0.          0.58894577  0.80558882  0.07400283]
 [ 0.          0.         -0.16270338  0.36767677 -0.03434621]
 [ 0.          0.         -0.16496733 -0.07727198 -0.75740885]]
[[ 0.98522742  0.18128525  0.60483977  0.27436262  0.77830831]
 [ 0.          0.84229211  0.59104384  0.08333311  0.79626919]
 [ 0.          0.          0.58894577  0.80558882  0.07400283]
 [ 0.          0.          0.          0.5902304  -0.01390204]
 [ 0.          0.          0.          0.1483784  -0.73668021]]
[[ 0.98522742  0.18128525  0.60483977  0.27436262  0

In [217]:
totL = listofl[0]
for i in range(columns-2):
    totL = totL.dot(listofl[i+1])
    print(totL)
totLinv = listoflinvs[len(listoflinvs) - 1]
for i in range(columns-2,-1,-1):
    totLinv = totLinv.dot(listoflinvs[i])
    print(totLinv)

[[1.         0.         0.         0.         0.        ]
 [0.25610804 1.         0.         0.         0.        ]
 [0.35847147 0.0434952  1.         0.         0.        ]
 [0.13249311 0.2355254  0.         1.         0.        ]
 [0.75830321 0.46032686 0.         0.         1.        ]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.25610804  1.          0.          0.          0.        ]
 [ 0.35847147  0.0434952   1.          0.          0.        ]
 [ 0.13249311  0.2355254  -0.27626207  1.          0.        ]
 [ 0.75830321  0.46032686 -0.28010614  0.          1.        ]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.25610804  1.          0.          0.          0.        ]
 [ 0.35847147  0.0434952   1.          0.          0.        ]
 [ 0.13249311  0.2355254  -0.27626207  1.          0.        ]
 [ 0.75830321  0.46032686 -0.28010614  0.25139063  1.        ]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.         

In [218]:
testU = np.matmul(totLinv,newtestmat)
testU

array([[ 9.85227419e-01,  1.81285246e-01,  6.04839767e-01,
         2.74362616e-01,  7.78308311e-01],
       [ 0.00000000e+00,  8.42292114e-01,  5.91043840e-01,
         8.33331094e-02,  7.96269186e-01],
       [-5.55111512e-17,  0.00000000e+00,  5.88945774e-01,
         8.05588824e-01,  7.40028277e-02],
       [ 0.00000000e+00,  2.77555756e-17,  0.00000000e+00,
         5.90230405e-01, -1.39020368e-02],
       [ 0.00000000e+00,  0.00000000e+00,  1.11022302e-16,
         5.55111512e-17, -7.33185364e-01]])

In [219]:
np.sum((totL.dot(testU) - testP.dot(testmat)) ** 2)

2.0848191647991828e-32

# IT WORKED
## let's make it into a function

In [222]:
def LUdecomp(matrix):
    dummytestmat = deepcopy(matrix)
    rows,columns = np.shape(matrix)
    listofl = []
    listoflinvs = []
    I = np.eye(rows,columns)
    for column in range(columns):
        tempL = deepcopy(I)
        tempLinv = deepcopy(I)
        for row in range(rows-column-1):
            tempL[row+1+column,column] = dummytestmat[row+1+column,column] / dummytestmat[column,column]
            tempLinv[row+1+column,column] = - dummytestmat[row+1+column,column] / dummytestmat[column,column]
        listofl.append(deepcopy(tempL))
        listoflinvs.append(deepcopy(tempLinv))
        dummytestmat = tempLinv.dot(dummytestmat)
    totL = listofl[0]
    for i in range(columns-2):
        totL = totL.dot(listofl[i+1])
    totLinv = listoflinvs[len(listoflinvs) - 1]
    for i in range(columns-2,-1,-1):
        totLinv = totLinv.dot(listoflinvs[i])
    testU = np.matmul(totLinv,matrix)
    return(totL, testU)

# Let's make sure it all works for a larger matrix

In [231]:
def alltogethernow(matrix):
    P = findP(matrix)
    newmat = P.dot(matrix)
    L, U = LUdecomp(newmat)
    print("here's the error:",np.sum((L.dot(U)-P.dot(matrix))**2))

In [232]:
testmat = np.random.rand(10,10)
alltogethernow(testmat)

here's the error: 3.159680666761699e-30


In [233]:
testmat = np.random.rand(100,100)
alltogethernow(testmat)

here's the error: 2.2080064829655245e-18


In [235]:
testmat = np.random.rand(200,200)
alltogethernow(testmat)

here's the error: 7.330885550835756e-17


In [236]:
testmat = np.random.rand(300,300)
alltogethernow(testmat)

here's the error: 9.474118009349769e-15


In [237]:
testmat = np.random.rand(400,400)
alltogethernow(testmat)

here's the error: 1.930335669575305e-13


# that's pretty neat! 
I don't know how I would've done this in less than two hours though lol the coding alone took 4. 